"""Saved, synthetic examples. No market price, design suitability or live analysis claims."""
from copy import deepcopy
from datetime import datetime, timezone, timedelta
from .calculations import fingerprint
from .decision_support import HISTORY,route_estimates

FIXTURE_VERSION='hopper-2026.09-v1'
STAGES=['Request','Requirements','Design & BOM','Manufacturing','Cost estimate','Risk','Price','Review & submit']
SCENARIOS={
 'seed':{'name':'Cedar Rapids Seed Co.','short':'Seed dealer','city':'Cedar Rapids, Iowa','tag':'Resolve the interface','description':'Indoor seed handling into an existing conveyor. Confirm the custom mating adapter before quoting.','quantity':'1','capacity':'3 m³','material':'Painted carbon steel','outlet':'200 mm manual gate + custom adapter','frame':'Anchored stationary frame','cover':'Open top + service access','environment':'Customer states dry indoor use; no washdown. Existing conveyor remains outside scope.','handled':'Dry seed','clarification':'Confirm the mating opening and bolt pattern from the customer drawing.','resolution':'Synthetic customer drawing C-101 R1 confirms 200 × 200 mm clear opening and 240 × 240 mm four-hole pattern.','material_options':['Painted carbon steel','Galvanized carbon steel'],'lead_days':'5'},
 'grain':{'name':'Mason City Grain Works','short':'Grain operator','city':'Mason City, Iowa','tag':'Navigate a shortage','description':'Larger covered hopper for explicitly stated outdoor use. Review shared gate stock and coating lead time.','quantity':'3','capacity':'8 m³','material':'Galvanized carbon steel','outlet':'300 mm flanged manual gate','frame':'Reinforced anchored frame','cover':'Weather cover + inspection hatch','environment':'Customer explicitly states outdoor rain exposure, unheated storage and seasonal operation. Wind/foundation loads require engineer review.','handled':'Dry grain','clarification':'Confirm site loading assumptions and outside coating availability.','resolution':'Synthetic engineering review E-202 R1 accepts demonstration load envelope only; coating supplier indicates 10 working days after fabricated parts are ready.','material_options':['Galvanized carbon steel','Painted carbon steel'],'lead_days':'10'},
 'feed':{'name':'Council Bluffs Feed Systems','short':'Feed processor','city':'Council Bluffs, Iowa','tag':'Protect the accepted margin','description':'Customer-defined cleaning requirements and stainless contact surfaces. See a supplier increase after acceptance.','quantity':'2','capacity':'5 m³','material':'304 stainless contact surfaces','outlet':'250 mm sanitary-access manual gate','frame':'Anchored stationary frame','cover':'Removable cover + cleanout panel','environment':'Customer states intermittent wet cleaning with a specified neutral detergent. No food-safety or chemical compatibility certification is asserted.','handled':'Dry feed blend','clarification':'Confirm cleaning chemistry and engineer-selected contact material.','resolution':'Synthetic customer cleaning sheet CS-3 identifies neutral detergent; illustrative engineering review approves the selected stainless candidate only for this demo. Real suitability remains subject to professional review.','material_options':['304 stainless contact surfaces','316 stainless contact surfaces'],'lead_days':'8'}
}

def now(): return datetime.now(timezone.utc).isoformat()
def source(id,title,content,kind='synthetic_shop',location='Section 1',visibility='internal'):
    return {'id':id,'title':title,'content':content,'kind':kind,'synthetic':True,'visibility':visibility,'location':location,'revision':'R1','hash':fingerprint(content),'retrieved_at':now(),'license':'Original fictional demonstration data; no external supplier evidence','status':'ready'}

def build(scenario, material=None):
    s=deepcopy(SCENARIOS[scenario]); material=material or s['material']; s['material']=material
    if material not in s['material_options']: raise ValueError('Unsupported material; needs live engineering review')
    stainless=scenario=='feed'; galvanized=material=='Galvanized carbon steel'; upgraded=material=='316 stainless contact surfaces'
    # Prices are full purchasing-pack prices, in USD. Specifications are illustrative.
    body=('BODY-316' if upgraded else 'BODY-304') if stainless else ('BODY-LG' if scenario=='grain' else 'BODY-SM')
    raw=[
      (body,'Body sheet kit','1','sheet','1','1','980' if upgraded else '740' if stainless else '620' if scenario=='grain' else '350','Prairie Metals',f'{material}; illustrative developed sheet kit; thickness per E-{scenario} R1'),
      ('FRAME-LG' if scenario=='grain' else 'FRAME-CS','Support frame kit','1','ea','1','1','410' if scenario=='grain' else '265','Iowa Structural',s['frame']+'; anchors/foundation excluded'),
      ('GATE-250-SS' if stainless else 'GATE-300' if scenario=='grain' else 'GATE-200','Manual outlet gate','1','ea','1','1','590' if stainless else '290' if scenario=='grain' else '210','Harvest Components',s['outlet']),
      ('ADAPTER-'+scenario.upper(),'Connection adapter','1','ea','1','1','240' if stainless else '180' if scenario=='seed' else '120','River Bend Fabrication','Drawing-controlled mating interface; no powered downstream design'),
      ('FASTENER','Assembly fasteners','18','ea','10','10','2.00','Midwest Fasteners','M8 fixture fasteners; pack of 10; engineering compatibility review required'),
      ('SEAL-SS' if stainless else 'SEAL-DRY','Gate seal kit','1','ea','1','1','68' if stainless else '24','Harvest Components','Demo candidate seal, cleaning compatibility per reviewed requirements'),
      ('COVER-'+scenario.upper(),'Cover/service package','1','ea','1','1','195' if stainless else '240' if scenario=='grain' else '45','River Bend Fabrication',s['cover']),
      ('PACK-'+scenario.upper(),'Shipping skid and wrap','1','ea','1','1','110' if scenario=='grain' else '80','Iowa Structural','Packaging only; freight excluded')]
    bom=[]; sources=[]
    for item,label,qty,unit,pack,moq,cost,supplier,spec in raw:
        src='offer-'+item.lower()
        bom.append({'item':item,'label':label,'per_unit':qty,'unit':unit,'pack':pack,'moq':moq,'pack_price':cost,'currency':'USD','supplier':supplier,'spec':spec,'source_id':src,'classification':'custom_buy' if 'ADAPTER' in item else 'standard_buy','drawing_ref':'drawing-'+scenario})
        sources.append(source(src,f'{supplier} · {label}',f'SYNTHETIC OFFER — {FIXTURE_VERSION}\nItem {item}; specification: {spec}.\nUSD {cost} per pack of {pack} {unit}; MOQ {moq} {unit}. Quantity tier: 1–12 assemblies. Prepared example availability: {s["lead_days"]} working days from approved order. Tax and freight EXCLUDED. Demo validity: 24 hours from loaded example. Not a real supplier quotation.','synthetic_supplier','Offer table, row '+item))
    route=[]
    ops=[('cut','Cut & prepare','0.6','0.45','82'),('form','Form body panels','0.8','0.65','90'),('weld','Fixture & weld','1.2','1.8' if stainless else '1.4','96'),('finish','Surface finish','0.3','0.9' if stainless else '0.6','88'),('assemble','Assemble gate & frame','0.4','0.8','72'),('inspect','Dimensional inspection','0.2','0.45','84'),('package','Package & stage','0.1','0.35','58')]
    for i,(id,label,setup,run,rate) in enumerate(ops):
        route.append({'id':id,'operation':label,'sequence':i+1,'dependencies':[ops[i-1][0]] if i else [],'work_center':label.split(' ')[0]+' cell','setup_hours':setup,'run_hours':run,'batch_limit':'4','loaded_rate':rate,'source_id':'route-'+scenario,'outside':False})
    if galvanized:
        # Outside coating is a purchased service, not a duplicate machine overhead charge.
        bom.append({'item':'COAT-ZN','label':'Outside galvanizing service','per_unit':'1','unit':'ea','pack':'1','moq':'1','pack_price':'225','currency':'USD','supplier':'Prairie Finishing','spec':'Illustrative approved coating package; dimensional allowance reviewed','source_id':'offer-coating','classification':'outside_service','drawing_ref':'drawing-'+scenario})
        sources.append(source('offer-coating','Prairie Finishing · Coating slot','SYNTHETIC: USD 225 per assembly; pack/MOQ 1. Ten working days after fabricated body ready, not from initial RFQ. Freight and tax excluded.'))
    sources += [
        source('request-'+scenario,'Customer request · synthetic transcript',f'SYNTHETIC CONVERSATION\nCustomer: {s["name"]}. We handle {s["handled"]}. {s["description"]}\nOperating conditions: {s["environment"]}\nCapacity: {s["capacity"]}. Interface: {s["outlet"]}.\nOpen clarification: {s["clarification"]}','synthetic_customer','Transcript paragraphs 1–4'),
        source('clarification-'+scenario,'Prepared clarification response',s['resolution'],'synthetic_customer','Response paragraph 1'),
        source('drawing-'+scenario,'Illustrative engineering drawing record',f'ILLUSTRATIVE ONLY — E-{scenario} R1.\n{material}; {s["capacity"]}; {s["outlet"]}; {s["frame"]}; {s["cover"]}.\nBOM is an estimating artifact. Plate thickness, detailed structural calculations, weld details and certification must be supplied by a qualified engineer before real manufacture. No autonomous CAD.','synthetic_engineering'),
        source('route-'+scenario,'Shop estimating route and loaded rates','SYNTHETIC SHOP RECORD\n'+ '\n'.join(f'{o["operation"]}: batch setup {o["setup_hours"]} h, run {o["run_hours"]} h/assembly, batch limit 4; loaded rate USD {o["loaded_rate"]}/h including labor and allocated work-center overhead.' for o in route)+'\nNormal scrap included in kit basis; no separate scrap multiplier. No double-added labor or overhead.'),
        source('inventory-ledger','Owned stock acquisition record','SYNTHETIC STOCK: 5 FASTENER at USD 0.10 each; 2 GATE-200 at USD 185 each; 1 FRAME-CS at USD 240. Each visitor receives an isolated demonstration shop. Quotes within the same session compete for the same lots. Holds do not consume stock.'),
        source('policy-v1','Demo commercial policy v1','Fictional policy: target gross margin 30%; quote validity 14 calendar days; stock holds 24 hours. Cost increase >5% or forecast margin <25% requires exception review. Freight/tax excluded. Payment: 50% deposit, balance before dispatch. No insurance payout assumptions. No contingency unless separately approved.'),
        source('history-'+scenario,'Analogous jobs · estimated vs actual','SYNTHETIC HISTORY: Two comparison jobs, H-'+scenario+'-1 and H-'+scenario+'-2, used different quantities or material/finish. They illustrate estimating context only. Their sale prices are not costs and are not selected in this estimate.'),
        source('alternate-'+scenario,'Alternate supplier · incompatible purchasing basis','SYNTHETIC alternate candidate: similar gate nominal size but different flange drilling and pack quantity. Status: incompatible pending engineering. Price intentionally unavailable; excluded from selected costs. No automatic substitution.')]
    support=route_estimates(scenario,material,s['quantity'],route, 'precision' if scenario in ('seed','feed') else 'flexible')
    engineering={'hours':'4','rate':'110','basis':'Custom adapter interface design and drafting'} if scenario=='seed' else {'hours':'6','rate':'120','basis':'Stainless contact details and cleaning-access drafting'} if scenario=='feed' else None
    sources += [source('historical-jobs-v1','Nine synthetic shop jobs · quoted versus actual',__import__('json').dumps(HISTORY,indent=2)),source('route-history-'+scenario,'Feature-derived route and analogous job comparison',__import__('json').dumps(support,indent=2)),source('shop-load-v1','Synthetic shop load by requested window','SYNTHETIC: 120 hours available each Mon–Fri work week. Relative to the visitor session’s US Central starting week: booked hours 84 in week 0, 102 in week 1, 72 in week 2 and 60 in other windows. This common shop calendar applies to all scenarios; it is not live ERP capacity.'),source('fixture-policy','Fixture allocation policy','SYNTHETIC: flexible tooling USD 90/project; batch fixture USD 360/project; precision interface fixture USD 220/project. Allocate once to project and display per-assembly cost divided by quantity. No double-counted setup charge.'),source('engineering-hours','Engineering and drafting basis',__import__('json').dumps(engineering or {'basis':'No incremental engineering/drafting line in the standard grain fixture.'}))]
    requirements=[{'field':k,'value':s[k],'status':'stated','source_id':'request-'+scenario} for k in ['handled','capacity','material','outlet','frame','cover','environment']]
    risks=[{'id':'engineering','title':s['clarification'],'owner':'Engineer','impact':'Critical feasibility','blocking':True,'disposition':'open','mitigation':s['resolution'],'source_id':'request-'+scenario}, {'id':'delivery','title':'Delivery depends on material and shop readiness','owner':'Production reviewer','impact':'Schedule','blocking':False,'disposition':'open','mitigation':'Qualify ready-to-ship forecast; verify capacity before confirming an order.','source_id':'route-'+scenario}, {'id':'commercial','title':'Freight and tax excluded; accepted price remains fixed','owner':'Estimator','impact':'Commercial','blocking':False,'disposition':'open','mitigation':'Customer terms disclose exclusions; refresh cost at acceptance.','source_id':'policy-v1'}]
    if scenario=='feed': risks.append({'id':'stale-history','title':'Historical carbon-steel price is not comparable to stainless contact surfaces','owner':'Estimator','impact':'Margin','blocking':False,'disposition':'open','mitigation':'Use current selected synthetic offers; refresh at acceptance with prepared price increase.','source_id':'history-'+scenario})
    risks.append({'id':'history-inspection','title':'A comparable synthetic job failed its first inspection','owner':'Quality / estimator','impact':'Inspection and rework','blocking':False,'disposition':'open','mitigation':('H-301 contact seam finish required rework; keep accessible finishing and reinspection in the route.' if scenario=='feed' else 'H-103 adapter flange position failed; verify fixture alignment and dimensional inspection before production.'),'source_id':'historical-jobs-v1'})
    return {'scenario':s,'bom':bom,'route':route,'base_route':deepcopy(route),'route_support':support,'route_choice':support['selected'],'route_overrides':{},'engineering':engineering,'fixture_cost':support['fixture_cost'],'historical_jobs':deepcopy(HISTORY),'sources':sources,'requirements':requirements,'risks':risks,'fixture_version':FIXTURE_VERSION}
