import React,{useEffect,useRef,useState} from 'react';
import './workflow.css';
type Row=Record<string,any>;
export async function getJSON(path:string){const r=await fetch('/api'+path);const data=await r.json();if(!r.ok)throw Error(data.error||data.detail||'Unable to load source');return data;}
export function Sheet({title,onClose,children}:{title:string,onClose:()=>void,children:React.ReactNode}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const prev=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const a=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,textarea,select,[tabindex="0"]');if(!a?.length)return;const first=a[0],last=a[a.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);prev?.focus();};},[]);
 return <div className="source-sheet-backdrop"><div ref={ref} className="source-sheet" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="secondary" onClick={onClose} aria-label="Close panel">Close ×</button></header>{children}</div></div>;
}
function Cell({value}:{value:any}){if(typeof value==='boolean')return <>{value?'Yes':'No'}</>;if(typeof value==='string'&&value.startsWith('https://'))return <a href={value} target="_blank" rel="noreferrer">{value} ↗</a>;return <>{typeof value==='object'?JSON.stringify(value):String(value??'—')}</>;}
export function DatabaseView({id,line,onClose}:{id:string,line?:number,onClose:()=>void}){
 const [db,setDb]=useState<Row|null>(null),[error,setError]=useState(''),[row,setRow]=useState<Row|null>(null);
 useEffect(()=>{setDb(null);setRow(null);getJSON('/databases/'+id).then(setDb).catch(e=>setError(e.message));},[id]);
 useEffect(()=>{if(db&&line)document.getElementById(`${id}-row-${line}`)?.scrollIntoView({block:'center'});},[db,line,id]);
 const cols=db?.rows.length?Object.keys(db.rows[0]).filter(k=>!['id','line'].includes(k)):[];
 return <Sheet title={db?`${id} · ${db.title}`:'Loading source…'} onClose={onClose}>{error&&<p role="alert">{error}</p>}{db&&<><p className="source-home">From {db.home} · demo copy</p><p>{db.status}</p><p className="micro">{db.path} · {db.version}</p>{db.note&&<div className="callout">{db.note}</div>}{db.view==='suppliers'&&<div className="supplier-grid">{db.rows.filter((r:Row)=>r.real_website).map((r:Row)=><a key={r.id} href={r.website} target="_blank" rel="noreferrer"><strong>{r.company} ↗</strong><span>{r.website}</span><small>{r.price_policy}</small></a>)}</div>}{['library','cards','records','folders'].includes(db.view)?<>{db.view==='folders'?['Won','Lost','In progress'].map(folder=><section key={folder}><h3>▱ {folder}</h3>{db.rows.filter((r:Row)=>r.folder===folder).map((r:Row)=><button className="source-record" id={`${id}-row-${r.line}`} key={r.id} onClick={()=>setRow(r)}>{r.quote} · {r.title} →</button>)}</section>):<div className="source-cards">{db.rows.map((r:Row)=><button className={'source-record '+(line===r.line?'citation-target':'')} id={`${id}-row-${r.line}`} key={r.id} onClick={()=>setRow(r)}>{r.image&&<img src={r.image} alt={r.title}/>}<strong>{r.material||r.title||r.company}</strong><small>Row {r.line} · {r.classification||'Fictional demo record'}</small>{r.oxidizer&&<b>Specialist engineering required</b>}</button>)}</div>}{row&&<article className="paper"><h2>{row.title||row.material||row.company}</h2><p>Prepared example · {row.id} · {db.version}</p>{Object.entries(row).filter(([k])=>k!=='image').map(([k,v])=><p key={k}><strong>{k.replaceAll('_',' ')}: </strong><Cell value={v}/></p>)}{db.view==='folders'&&<button onClick={()=>window.print()}>Print / Save PDF</button>}</article>}</>:<div className="source-grid" role="region" aria-label={db.title+' rows'} tabIndex={0}><table><thead><tr><th>Row</th>{cols.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{db.rows.map((r:Row)=><tr className={line===r.line?'citation-target':''} id={`${id}-row-${r.line}`} key={r.id}><th>{r.line}<small>{r.id}</small></th>{cols.map(k=><td key={k}><Cell value={r[k]}/></td>)}</tr>)}</tbody></table></div>}</>}</Sheet>;
}
export function DataSources(){const [dbs,setDbs]=useState<Row[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState('');useEffect(()=>{getJSON('/databases').then(setDbs).catch(e=>setError(e.message));},[]);return <section><div className="section-kicker">FOLLOW THE EVIDENCE</div><h1>Data sources</h1><p className="page-intro">Every source has a home, a stable record ID and a visible boundary. Provider documents are fictional demo copies stored in Supabase.</p>{error&&<p role="alert">{error}</p>}<div className="source-map">{['Excel / Google Drive','Conversations','CRM','Supabase'].map((group,i)=><section key={group}><h2>{group}</h2>{dbs.filter(d=>i===0?Number(d.id.slice(1))<=9||d.id==='D12':i===1?d.id==='D11':i===2?d.id==='D10':d.id==='D13').map(d=><button key={d.id} onClick={()=>setSelected(d.id)}><b>{d.id}</b><span>{d.title}<small>{d.home} · {d.id==='D13'?'Versioned storage':'demo copy'}</small></span><span>↗</span></button>)}</section>)}</div><div className="source-map"><section><h2>Python calculator</h2><p>Real deterministic calculations. Costs, quantities, margin and time are calculated on the server.</p></section><section><h2>MCP AI host</h2><p>Prepared examples by default. Live mode waits for a separately connected host. No recorded AI run is claimed.</p></section></div>{selected&&<DatabaseView id={selected} onClose={()=>setSelected('')}/>}</section>;}
