"""Versioned fictional source seed; arithmetic is computed here, never in the UI."""
from backend.fixtures import build, SCENARIOS
from backend.decision_support import HISTORY
from backend.calculations import dec, money

VERSION = '2026.09.30-v2'
NOTICE = 'Pre-written fictional demo document stored in Supabase. No live provider sync.'

def database(id, title, home, view, rows, note=''):
    return dict(id=id,title=title,home=home,view=view,version=VERSION,status=NOTICE,path=f'Demo shop/{title}',note=note,rows=[dict(id=f'{id}-{i:03}',line=i,**row) for i,row in enumerate(rows,1)])

def seed_databases():
    b=build('seed'); out=[]
    out.append(database('D1','Master inventory','Excel · Master inventory.xlsx','spreadsheet',[
        dict(stock_number='LOT-'+item,item=item,spec=spec,qty_on_hand=qty,qty_held='0',company='Fictional shop supplier',product_url=url,unit_price_paid=cost,lot_total=money(dec(qty)*dec(cost)),purchase_date='2026-06-02')
        for item,spec,qty,cost,url in [('FASTENER','M8 fixture fasteners','5','0.10','https://www.mcmaster.com/fasteners/'),('GATE-200','200 mm manual gate','2','185',''),('FRAME-CS','Carbon steel frame','1','240','')]],'In a live deployment this sheet syncs from the master inventory. Session stock and holds are shown separately in the cost step.'))
    suppliers=[('McMaster-Carr','https://www.mcmaster.com/','Fasteners, seals and hardware'),('Grainger','https://www.grainger.com/','Industrial components and maintenance'),('Fastenal','https://www.fastenal.com/','Fasteners and shop supplies'),('MSC Industrial Direct','https://www.mscdirect.com/','Tooling and industrial supplies'),('OnlineMetals','https://www.onlinemetals.com/','Plate and raw metal')]
    out.append(database('D2','Trusted suppliers','Excel on Google Drive · Suppliers.xlsx','suppliers',[
        dict(company=n,website=u,supplies=s,account_note='Fictional demo account; no contract or endorsement',typical_lead_time='Prepared planning assumption: 5 business days; confirm with supplier',real_website=True,price_policy='Demo price · not taken from this page') for n,u,s in suppliers]+[
        dict(company=n,website='',supplies=s,account_note='Fictional local supplier',typical_lead_time='Demo: 5 business days',real_website=False) for n,s in [('River Bend Fabrication','Custom adapters'),('Harvest Components','Gate assemblies'),('Iowa Structural','Frames and packaging'),('Midwest Fasteners','Fasteners')]]))
    out.append(database('D3','Labor rates','Excel on Google Drive · Labor rates.xlsx','spreadsheet',[dict(task=o['operation'],hourly_rate=o['loaded_rate'],currency='USD',includes='Labor and allocated work-center overhead; fixed demo rate') for o in b['base_route']]))
    out.append(database('D4','Past projects & completion data','Google Drive','table',[dict(job=j['id'],task='All operations',quoted_hours=j['quoted_hours'],actual_hours=j['actual_hours'],variance_hours=money(dec(j['actual_hours'])-dec(j['quoted_hours'])),notes=j['inspection_note'],basis=j['actual_basis']) for j in HISTORY],'Future completion extraction proposes new records after fulfillment; no extraction is running.'))
    out.append(database('D5','Historical BOM database','Google Drive','table',[dict(job='Template-'+sid,part=x['item'],spec=x['spec'],material=SCENARIOS[sid]['material'],qty_per_assembly=x['per_unit']) for sid in SCENARIOS for x in build(sid)['bom']]))
    out.append(database('D6','Past quotes','Google Drive · Won / Lost / In progress','folders',[dict(quote=j['id'],folder='In progress' if j['id']=='H-303' else j['win_loss'].title(),title='Fictional '+j['scenario']+' hopper quote',quantity=j['quantity'],material=j['material'],terms='Freight and tax excluded. Drawing review required.',price='Historical price unavailable; never use as a current cost.',basis=j['actual_basis']) for j in HISTORY]))
    out.append(database('D7','Design templates','Google Drive','cards',[dict(design=sid,title=s['capacity']+' hopper concept',material=s['material'],image='/assets/concept-'+sid+'.png',classification='AI concept · not an engineering drawing',review='Structural calculations, welding details and manufacture-ready drawings require qualified engineering.') for sid,s in SCENARIOS.items()]))
    out.append(database('D8','Manufacturing process docs','Google Drive','document',[dict(sequence=i,operation=op,machine=machine,note=note) for i,(op,machine,note) in enumerate([('Legs','Saw and weld fixture','Confirm anchored stationary frame.'),('Cone','Cutting table and press brake','Review slope and interface.'),('Body','Press brake and welding cell','Check seams and access.'),('Gate','Assembly bench','Verify flange and bolt pattern.'),('Finish','Finishing cell','Use reviewed material/finish route.'),('Inspect','Dimensional inspection','Inspect adapter alignment before packing.')],1)]))
    material_data=[
        ('Corn / grain dust','Mild','No general corrosion claim','St1; Kst approx. 100–160 per research summary, not a design value',False,'Moisture can cause bridging','Not established','Dust testing and hazard review; confirm flow properties','Dust control and engineering review'),
        ('Urea','Low','Material compatibility review required','Not classified here; obtain product SDS',False,'Hygroscopic; clumping around 1% moisture per research summary','Not established','Confirm moisture exposure and enclosure needs','Moisture controls and compatible surfaces'),
        ('Ammonium nitrate','Low','Compatibility review required','Oxidizer hazard; do not treat as ordinary combustible dust',True,'Hygroscopic and caking','Not established','Specialist engineering required; outside supported hopper demo configurations','Specialist study; no estimated safety-system prices'),
        ('Sand / gravel','High','Product dependent','Mineral dust; obtain sample/SDS; do not assume harmless',False,'Moisture and grading affect flow','Not established','Review wear, loads and respiratory dust','Wear liners and structural review'),
        ('DDGS','Moderate','Product dependent','Combustible organic dust; test sample',False,'Cohesive; bridging risk','Approx. 48° per research summary; not a hopper slope','Flow testing and combustible dust review','Flow aids and hazard review'),
        ('Potash','Moderate','Salt corrosion risk','Obtain product SDS and contamination assessment',False,'Hygroscopic; caking when damp','Not established','Review corrosion and moisture exposure','Compatible coatings and moisture control')]
    out.append(database('D9','Bulk material library','Google Drive','library',[dict(material=n,abrasiveness=a,corrosiveness=c,dust_class=d,oxidizer=o,hygroscopic_caking=h,angle_of_repose=r,bulk_density='Unknown; confirm sample and units',design_implications=imp,cost_adders=add,standards_to_check='NFPA 400; OSHA 1910.109(i)' if o else 'NFPA 61/652 historical references; NFPA 660 consolidation; OSHA 1910.272 where applicable',sources='Bulk Materials Handling Classifications and Design Impacts · per research summary; no checkable report URLs',standards_url='https://www.osha.gov/fertilizer-industry' if o else 'https://www.nfpa.org/codes-and-standards/nfpa-660-standard-development/660',classification='reference summary · engineering review required') for n,a,c,d,o,h,r,imp,add in material_data]))
    out.append(database('D10','CRM','CRM (system unnamed)','records',[dict(scenario=sid,company=s['name'],relationship='Returning client' if sid=='seed' else 'New client',past_jobs='H-101, H-102' if sid=='seed' else 'None confirmed',contact='Fictional purchasing contact; no personal details') for sid,s in SCENARIOS.items()]))
    conversations=[]
    for sid,s in SCENARIOS.items():
        conversations += [dict(scenario=sid,type='Granola · call transcript',content=s['description']+' '+s['environment']),dict(scenario=sid,type='Gmail · request email',content=f"Please quote {s['quantity']} hopper assemblies; capacity {s['capacity']}. {s['clarification']}"),dict(scenario=sid,type='Web survey',content=f"Handled material: {s['handled']}. Construction: {s['material']}. Outlet: {s['outlet']}."),dict(scenario=sid,type='Gmail · clarification response',content=s['resolution'])]
    out.append(database('D11','Conversations','Granola (calls) · Gmail (emails) · web survey','document',conversations))
    out.append(database('D12','Client document','Google Drive','document',[dict(scenario=sid,company=s['name'],background='Fictional '+s['short']+'; no real company research claimed',requirements=s['description'],environment=s['environment'],gap=s['clarification'],version_history='v1: submitted requirements. v2: after explicit customer-answer confirmation.') for sid,s in SCENARIOS.items()]))
    out.append(database('D13','Agent instructions','Supabase (real)','playbooks',[dict(name=p.stem,text=p.read_text(),version='1.0') for p in sorted(__import__('pathlib').Path('backend/playbooks').glob('*.md')) if p.stem!='README'],'Exact versioned instructions; prepared examples are not recorded AI runs.'))
    return out
