"""Repeatable original synthetic source artifacts. Never label these Recorded AI runs."""
from pathlib import Path
from uuid import uuid5,NAMESPACE_URL
from datetime import datetime,timezone
import sys,json
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from backend.fixtures import SCENARIOS,FIXTURE_VERSION
from backend.domain import create_quote,bind_session,package,act
from backend.pdf_export import customer_pdf
root=Path('fixtures')
for sid,s in SCENARIOS.items():
    folder=root/sid;folder.mkdir(parents=True,exist_ok=True)
    q=bind_session(create_quote({'scenario':sid,'description':s['description'],'quantity':s['quantity'],'company':s['name'],'contact':'Prepared example recipient','mode':'guided_demo','event_key':'source-pack-'+sid}),{'id':'source-pack-session','created_at':'2026-09-30T05:00:00+00:00'})
    q['id']=str(uuid5(NAMESPACE_URL,'arc:'+FIXTURE_VERSION+':'+sid))
    for source in q['sources']:
        (folder/(source['id']+'.md')).write_text('# '+source['title']+'\n\n**Prepared example · SYNTHETIC · '+FIXTURE_VERSION+'**\n\nSource ID: '+source['id']+' · '+source['location']+'\n\n'+source['content']+'\n')
    data={k:q[k] for k in ['scenario','fixture_version','requirements','bom','route','route_support','engineering','historical_jobs','calculation','pricing_options','schedule','risks','terms']}
    data['classification']='Prepared example — synthetic; no real approval or Recorded AI run'
    (folder/'structured-fixture.json').write_text(json.dumps(data,indent=2))
    p=package(q);(folder/'prepared-customer-quote.pdf').write_bytes(customer_pdf(p))
(root/'README.md').write_text('# Original synthetic source pack\n\nThree coherent prepared examples generated by `scripts/build_source_pack.py`. These are not Recorded AI runs, market offers, certified engineering or real commercial documents. Source IDs and fixture version link to the app’s scoped runtime records. Session-relative source dates are regenerated by the application for each visitor; this pack uses an explicit reference session at 2026-09-30 00:00 US Central.\n')
print('Generated three labeled source packs with nine historical jobs, route comparisons, cost/pricing snapshots and customer PDFs.')
